// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TiaGenerator.Templates
{
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TemplateBlockFC : TemplateBlockFCBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Document>\n  <Engineering version=\"V17\"/>\n  <DocumentInfo>\n    <Created>2023-03-16T18:56:23.8618408Z</Created>\n    <ExportSetting>None</ExportSetting>\n    <InstalledProducts>\n      <Product>\n        <DisplayName>Totally Integrated Automation Portal</DisplayName>\n        <DisplayVersion>V17 Update 5</DisplayVersion>\n      </Product>\n      <OptionPackage>\n        <DisplayName>TIA Portal Openness</DisplayName>\n        <DisplayVersion>V17 Update 5</DisplayVersion>\n      </OptionPackage>\n      <OptionPackage>\n        <DisplayName>TIA Portal Version Control Interface</DisplayName>\n        <DisplayVersion>V17</DisplayVersion>\n      </OptionPackage>\n      <OptionPackage>\n        <DisplayName>TIA Portal Test Suite Advanced</DisplayName>\n        <DisplayVersion>V17 Update 1</DisplayVersion>\n      </OptionPackage>\n      <Product>\n        <DisplayName>STEP 7 Professional</DisplayName>\n        <DisplayVersion>V17 Update 5</DisplayVersion>\n      </Product>\n      <OptionPackage>\n        <DisplayName>STEP 7 Safety</DisplayName>\n        <DisplayVersion>V17</DisplayVersion>\n      </OptionPackage>\n      <Product>\n        <DisplayName>WinCC Advanced</DisplayName>\n        <DisplayVersion>V17 Update 5</DisplayVersion>\n      </Product>\n    </InstalledProducts>\n  </DocumentInfo>\n  <SW.Blocks.FC ID=\"0\">\n    <AttributeList>\n      <AutoNumber>");
            
            #line 42 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AutoNumber.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("</AutoNumber>\n      <HeaderAuthor>");
            
            #line 43 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Author));
            
            #line default
            #line hidden
            this.Write("</HeaderAuthor>\n      <HeaderFamily>");
            
            #line 44 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Family));
            
            #line default
            #line hidden
            this.Write("</HeaderFamily>\n      <Interface>\n        <Sections xmlns=\"http://www.siemens.com/automation/Openness/SW/Interface/v5\">\n          <Section Name=\"Input\" />\n          <Section Name=\"Output\" />\n          <Section Name=\"InOut\" />\n          <Section Name=\"Temp\" />\n          <Section Name=\"Constant\" />\n          <Section Name=\"Return\">\n            <Member Name=\"Ret_Val\" Datatype=\"Void\" />\n          </Section>\n        </Sections>\n      </Interface>\n      <MemoryLayout>Optimized</MemoryLayout>\n      <Name>");
            
            #line 58 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BlockName));
            
            #line default
            #line hidden
            this.Write("</Name>\n      <Number>");
            
            #line 59 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BlockNumber));
            
            #line default
            #line hidden
            this.Write("</Number>\n      <ProgrammingLanguage>LAD</ProgrammingLanguage>\n      <SetENOAutomatically>false</SetENOAutomatically>\n    </AttributeList>\n    <ObjectList>\n      <MultilingualText ID=\"1\" CompositionName=\"Comment\">\n        <ObjectList>\n          <MultilingualTextItem ID=\"2\" CompositionName=\"Items\">\n            <AttributeList>\n              <Culture>de-DE</Culture>\n              <Text />\n            </AttributeList>\n          </MultilingualTextItem>\n        </ObjectList>\n      </MultilingualText>\n\n      <!-- Generated Stuff -->\n");
            
            #line 76 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"

    foreach (var network in Networks)
    {

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 80 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(network));
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 81 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"

    }

            
            #line default
            #line hidden
            this.Write("      <!-- Generated Stuff -->\n      \n      <MultilingualText ID=\"3\" CompositionName=\"Title\">\n        <ObjectList>\n          <MultilingualTextItem ID=\"4\" CompositionName=\"Items\">\n            <AttributeList>\n              <Culture>de-DE</Culture>\n              <Text>");
            
            #line 91 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BlockName));
            
            #line default
            #line hidden
            this.Write("</Text>\n            </AttributeList>\n          </MultilingualTextItem>\n        </ObjectList>\n      </MultilingualText>\n    </ObjectList>\n  </SW.Blocks.FC>\n</Document>\n\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 100 "/Users/jan/RiderProjects/TiaGenerator/TiaGenerator/TiaGenerator/Templates/TemplateBlockFC.tt"

    public bool AutoNumber { get; set; }
    public string Author { get; set; } = string.Empty;
    public string Family { get; set; } = string.Empty;
    public string BlockName { get; set; } = null!;
    public int BlockNumber { get; set; }
    public List<string> Networks { get; set; } = new();

    public TemplateBlockFC()
    {
    }

    public TemplateBlockFC(string author, string blockName, int blockNumber, bool autoNumber, string family)
    {
        Author = author;
        BlockName = blockName;
        BlockNumber = blockNumber;
        AutoNumber = autoNumber;
        Family = family;
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TemplateBlockFCBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
